src/models/Feedback.py
from main import db
from datetime import datetime


class Feedback(db.Model):
    __tablename__ = 'feedbacks'

    id = db.Column(db.Integer, primary_key=True)
    text = db.Column(db.String(), nullable=False)
    last_updated = db.Column(
        db.DateTime,
        default=datetime.now,
        onupdate=datetime.now
    )
    project_id = db.Column(
        db.Integer,
        db.ForeignKey('projects.id'),
        nullable=False
    )
    user_id = db.Column(
        db.Integer,
        db.ForeignKey('users.id'),
        nullable=False
    )

src/models/Project.py
from main import db
from datetime import datetime


class Project(db.Model):
    __tablename__ = 'projects'

    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String())
    link = db.Column(db.String())
    description = db.Column(db.String())
    last_updated = db.Column(
        db.DateTime,
        default=datetime.now,
        onupdate=datetime.now
    )
    user_id = db.Column(
        db.Integer,
        db.ForeignKey('users.id'),
        nullable=False
    )
    feedbacks = db.relationship(
        'Feedback',
        backref='project',
        cascade='all, delete'
    )

src/controllers/auth_controller.py
from models.User import User
from main import db
from flask import Blueprint, request, render_template, redirect, url_for, flash
from main import bcrypt
from flask_login import login_user, logout_user, login_required

auth = Blueprint('auth', __name__)


@auth.route('/', methods=['GET'])
def main_page():
    return redirect(url_for('projects.project_index'))


@auth.route('/auth/register', methods=['POST'])
def auth_register():
    username = request.form.get('username')
    email = request.form.get('email')
    password = request.form.get('password')

    user = User.query.filter_by(username=username).first()
    if user:
        flash('Username already in use. Please try another.')
        return redirect(url_for('auth.signup'))

    user = User.query.filter_by(email=email).first()
    if user:
        flash('Email already in use. Please try another.')
        return redirect(url_for('auth.signup'))

    user = User()
    user.username = username
    user.email = email
    user.password = bcrypt.generate_password_hash(password).decode('utf-8')

    db.session.add(user)
    db.session.commit()

    flash('You are now registered. Please sign in here')

    # return jsonify(user_schema.dump(user))
    return redirect(url_for('auth.login'))


@auth.route('/auth/login', methods=['POST'])
def auth_login():
    username = request.form.get('username')
    password = request.form.get('password')

    user = User.query.filter_by(username=username).first()

    if not user or not bcrypt.check_password_hash(user.password, password):
        flash('Invalid Credentials')
        return redirect(url_for('auth.login'))

    login_user(user)
    # return jsonify(user_schema.dump(user))
    flash(f'Welcome {user.username}, you are now signed in')
    return redirect(url_for('projects.project_index'))


@auth.route('/signup', methods=['GET'])
def signup():
    return render_template('signup.html')


@auth.route('/login', methods=['GET'])
def login():
    return render_template('login.html')


@auth.route('/logout', methods=['GET'])
@login_required
def logout():
    logout_user()
    flash('You are now signed out')
    return redirect(url_for('projects.project_index'))

src/controllers/feedbacks_controller.py
from models.Feedback import Feedback
from models.Project import Project
from main import db
from flask import Blueprint, request, render_template, redirect, url_for, flash
from flask_login import login_required, current_user

feedbacks = Blueprint('feedbacks', __name__, url_prefix='/feedback')


@feedbacks.route('/project/<int:id>', methods=['POST'])
@login_required
def feedback_create(id):
    project = Project.query.filter_by(id=id).first()

    feedback = Feedback.query.filter_by(
        user_id=current_user.id,
        project_id=project.id
    ).first()

    if feedback:
        flash('Already given feedback in this project')
        return redirect(url_for('feedbacks.feedback_show_project', id=id))

    if project.user_id == current_user.id:
        flash('Cannot give feedback on your own project')
        return redirect(url_for('feedbacks.feedback_show_project', id=id))

    new_feedback = Feedback()
    new_feedback.text = request.form.get('text')
    new_feedback.user_id = current_user.id
    new_feedback.project_id = project.id

    db.session.add(new_feedback)
    db.session.commit()

    flash('Thank you for your Feedback')
    # return jsonify(feedback_schema.dump(new_feedback))
    return redirect(url_for('feedbacks.feedback_show_project', id=id))


@feedbacks.route('/<int:id>', methods=['GET'])
def feedback_show(id):
    feedback = Feedback.query.get(id)

    # return jsonify(feedback_schema.dump(feedback))
    return render_template("feedback.html", feedback=feedback)


@feedbacks.route('/project/<int:id>', methods=['GET'])
def feedback_show_project(id):
    feedbacks = Feedback.query.filter_by(project_id=id)
    project = Project.query.get(id)

    # return jsonify(feedbacks_schema.dump(feedback))
    return render_template(
        "feedback_index.html",
        feedbacks=feedbacks,
        project_name=project.name,
        project_id=id
    )


# @feedbacks.route('/<int:id>', methods=['DELETE'])
@feedbacks.route("/delete/<int:id>", methods=["GET"])
@login_required
def feedback_delete(id):
    feedback = Feedback.query.filter_by(id=id, user_id=current_user.id).first()

    if not feedback:
        flash('Unauthorised to delete this feedback')
        return redirect(url_for('feedbacks.feedback_show', id=id))

    project_id = feedback.project_id

    db.session.delete(feedback)
    db.session.commit()

    flash('Feedback Deleted')

    return redirect(url_for('feedbacks.feedback_show_project', id=project_id))


# @feedbacks.route('/<int:id>', methods=['PUT', 'PATCH'])
@feedbacks.route("/update/<int:id>", methods=["POST"])
@login_required
def feedback_update(id):
    feedback = Feedback.query.filter_by(id=id, user_id=current_user.id).first()

    if not feedback:
        flash('Unauthorised to update this feedback')
        return redirect(url_for('feedbacks.feedback_show', id=id))

    feedback.text = request.form.get('text')

    db.session.commit()

    flash('Feedback Updated')

    return redirect(url_for('feedbacks.feedback_show', id=id))


@feedbacks.route("/new/<int:id>", methods=["GET"])
def new_feedback(id):
    return render_template("new_feedback.html", id=id)


@feedbacks.route("/revise/<int:id>", methods=["GET"])
def revise_feedback(id):
    feedback = Feedback.query.get(id)
    return render_template("revise_feedback.html", feedback=feedback)

src/controllers/projects_controller.py
from models.Project import Project
from main import db
from flask import Blueprint, request, render_template, redirect, url_for, flash
from flask_login import login_required, current_user

projects = Blueprint('projects', __name__, url_prefix='/projects')


@projects.route('/', methods=['GET'])
def project_index():
    projects = Project.query.all()

    # return jsonify(projects_schema.dump(projects))
    return render_template("projects_index.html", projects=projects)


@projects.route('/', methods=['POST'])
@login_required
def project_create():
    name = request.form.get('name')
    link = request.form.get('link')
    description = request.form.get('description')

    new_project = Project()
    new_project.name = name
    new_project.link = link
    new_project.description = description
    new_project.user_id = current_user.id

    db.session.add(new_project)
    db.session.commit()

    flash('Project Created!')
    # return jsonify(project_schema.dump(new_project))
    return redirect(url_for('projects.project_show', id=new_project.id))


@projects.route('/<int:id>', methods=['GET'])
def project_show(id):
    project = Project.query.get(id)

    # return jsonify(project_schema.dump(project))
    return render_template("project.html", project=project)


@projects.route('/my_projects', methods=['GET'])
@login_required
def project_show_user():
    projects = Project.query.filter_by(user_id=current_user.id)

    # return jsonify(projects_schema.dump(projects))
    return render_template("projects_user.html", projects=projects)


# @projects.route('/<int:id>', methods=['DELETE'])
@projects.route("/delete/<int:id>", methods=['GET'])
@login_required
def project_delete(id):
    project = Project.query.filter_by(id=id, user_id=current_user.id).first()

    if not project:
        flash('Unauthorised to delete this project')
        return redirect(url_for('projects.project_show', id=id))

    db.session.delete(project)
    db.session.commit()

    flash('Project Deleted')
    return redirect(url_for('projects.project_show_user'))


# @projects.route('/<int:id>', methods=['PUT', 'PATCH'])
@projects.route("/update/<int:id>", methods=['POST'])
@login_required
def project_update(id):
    project = Project.query.filter_by(id=id, user_id=current_user.id).first()

    if not project:
        flash('Unauthorised to update this project')
        return redirect(url_for('projects.project_show', id=id))

    project.name = request.form.get('name')
    project.link = request.form.get('link')
    project.description = request.form.get('description')

    db.session.commit()

    flash('Project Updated')
    # return jsonify(project_schema.dump(project))
    return redirect(url_for('projects.project_show', id=id))


@projects.route("/new", methods=["GET"])
def new_project():
    return render_template("new_project.html")


@projects.route("/revise/<int:id>", methods=["GET"])
def revise_project(id):
    project = Project.query.get(id)
    return render_template("revise_project.html", project=project)

src/templates/feedback.html
{% extends "layout.html" %}

{% block content%}
    {% if feedback %}
        <div class="card text-center border-dark mb-3">
            <div class="card-header">
                Feedback from {{feedback.user.username}}
            </div>
            <div class="card-body">
                <h5 class="card-title">{{feedback.project.name}}</h5>
                <p class="card-text">{{feedback.text}}</p>
                <a href="{{ url_for('projects.project_show', id=feedback.project.id) }}" class="btn btn-primary">See this Project</a>
            </div>
            <div class="card-footer text-muted">
                Last updated: {{feedback.last_updated.strftime('%Y-%m-%d %H:%M')}}
            </div>
            {% if current_user.is_authenticated and current_user.id == feedback.user_id %}
                <a href="{{ url_for('feedbacks.revise_feedback', id=feedback.id) }}" class="btn btn-success">Update Feedback</a>
                <a href="{{ url_for('feedbacks.feedback_delete', id=feedback.id) }}" class="btn btn-danger">Delete Feedback</a>
            {% endif %}
            <a href="{{ url_for('feedbacks.feedback_show_project', id=feedback.project_id) }}" class="btn btn-primary">More Feedback</a>
        </div>
    {% else %}
        <div class="card text-center border-dark mb-3">
            <div class="card-body">
                <h5 class="card-title">This Project has been removed</h5>
                <a href="{{ url_for('projects.project_index') }}" class="btn btn-primary">Return</a>
            </div>
        </div>
    {% endif %}
{% endblock %}

src/templates/feedback_index.html
{% extends "layout.html" %}

{% block content%}
    <div class="card text-center text-dark bg-light mb-3 border-dark mb-3">
        <div class="card-body">
            <h1 class="card-title">Feedback for {{project_name}}</h1>
        </div>
    </div>
    {% for feedback in feedbacks %}
        <div class="card text-center border-dark mb-3">
            <div class="card-header">
                Feedback from {{feedback.user.username}}
            </div>
            <div class="card-body">
                <h5 class="card-title">{{feedback.project.name}}</h5>
                <p class="card-text">{{feedback.text}}</p>
            </div>
            <div class="card-footer text-muted">
                Last updated: {{feedback.last_updated.strftime('%Y-%m-%d %H:%M')}}
            </div>
            <a href="{{ url_for('feedbacks.feedback_show', id=feedback.id) }}" class="btn btn-primary">More...</a>
        </div>
    {% endfor %}
    <a href="{{ url_for('feedbacks.new_feedback', id=project_id) }}" class="btn btn-primary">Give Feedback</a>
    <a href="{{ url_for('projects.project_show', id=project_id) }}" class="btn btn-primary">Back to Project</a>
{% endblock %}

src/templates/layout.html
<!DOCTYPE html>
<html>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <head>
        <title>
            T4A2-B: Eric C
        </title>
    </head>
    <body>
        <header>
            <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
                <div class="container-fluid">
                    <a class="navbar-brand" href="https://github.com/eric-chew/T4A2-B">T4A2-B Source Code</a>
                    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
                        <span class="navbar-toggler-icon"></span>
                    </button>
                    <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
                        <div class="navbar-nav">
                            <a class='nav-link' href="/projects">All Projects</a>
                            {% if current_user.is_authenticated %}
                                <a class='nav-link' href="/projects/new">Create a new Project</a>
                                <a class='nav-link' href="/projects/my_projects">View your Projects</a>
                                <a class='nav-link' href="/logout">Log out</a>
                            {% else %}
                                <a class='nav-link' href="/signup">Sign up</a>
                                <a class='nav-link' href="/login">Log in</a>
                            {% endif %}
                            {% if current_user.is_authenticated %}
                                <span class="navbar-text">
                                    Logged in as {{current_user.username}}
                                </span>
                            {% endif %}
                        </div>
                    </div>
                </div>
            </nav>
            {% with messages = get_flashed_messages() %}
                {% if messages %}
                    {% for msg in messages %}
                       <div class="alert alert-warning" role="alert">{{msg}}</div>
                    {% endfor %}
                {% endif %}
            {% endwith %}
        </header>
        <div class="container">
            {% block content %}
    
            <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
            <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
            <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
            </div>
            {% endblock %}
        </div>
    </body>
</html>

src/templates/login.html
{% extends 'layout.html' %}

{% block content %}
    <div class="card text-center text-dark bg-light mb-3 border-dark mb-3">
        <div class="card-body">
            <h1 class="card-title">Log In</h1>
        </div>
    </div>
    <div>
        <div>
            <form action="{{ url_for('auth.auth_login') }}" method='POST'>
                <div class="mb-3">
                    <label for="username" class="form-label">Username</label>
                    <input type='text' class="form-control" name='username' id='username' placeholder='Username' autofocus=''>
                </div>
                <div class="mb-3">
                    <label for="password" class="form-label">Password</label>
                    <input type="password" class="form-control" name='password' id="password">
                </div>
                <button type="submit" class="btn btn-primary">Log In</button>
                <a href="{{ url_for('auth.main_page') }}"><buttontype="button" class="btn btn-success">Go Back</button></a>
            </form>
        </div>
    </div>
{% endblock %}

src/templates/new_feedback.html
{% extends "layout.html" %}

{% block content %}
    <div class="card text-center text-dark bg-light mb-3 border-dark mb-3">
        <div class="card-body">
            <h1 class="card-title">Give Feedback</h1>
        </div>
    </div>
    {% if current_user.is_authenticated %}
    <div>
        <div>
            <form action="{{ url_for('feedbacks.feedback_create', id=id) }}" method="POST">
                <div class="mb-3">
                    <label for="text" class="form-label">Feedback: </label>
                    <textarea class="form-control" name='text' id='text' placeholder='Feedback...' rows='12' autofocus=''></textarea>
                </div>
                <button type="submit" class="btn btn-primary">Submit Feedback</button>
                <a href="{{ url_for('projects.project_index') }}"><buttontype="button" class="btn btn-success">Back to Projects</button></a>
            </form>
        </div>
    </div>
    {% else %}
    <div class="card text-center text-dark bg-warning mb-3">
        <div class="card-body">
            <h5 class="card-title">Please sign in to give Feedback</h5>
            <a href="{{ url_for('auth.login') }}"><buttontype="button" class="btn btn-success">Log In</button></a>
            <a href="{{ url_for('auth.signup') }}"><buttontype="button" class="btn btn-success">Sign Up</button></a>
            <a href="{{ url_for('projects.project_index') }}"><buttontype="button" class="btn btn-success">Back to Projects</button></a>
        </div>
    </div>
    {% endif %}
    
{% endblock %}

src/templates/new_project.html
{% extends "layout.html" %}

{% block content %}
    <div class="card text-center text-dark bg-light mb-3 border-dark mb-3">
        <div class="card-body">
            <h1 class="card-title">Create Project</h1>
        </div>
    </div>
    {% if current_user.is_authenticated %}
    <div>
        <div>
            <form action="{{ url_for('projects.project_create') }}" method="POST">
                <div class="mb-3">
                    <label for="name" class="form-label">Project Name: </label>
                    <input type='text' class="form-control" name='name' id='name' placeholder='Project Name' autofocus=''>
                </div>
                <div class="mb-3">
                    <label for="link" class="form-label">Link: </label>
                    <input type='url' class="form-control" name='link' id='link' placeholder='Link'>
                </div>
                <div class="mb-3">
                    <label for="description" class="form-label">Description: </label>
                    <textarea class="form-control" name='description' id='description' placeholder='Project Description...' rows='10'></textarea>
                </div>
                <button type="submit" class="btn btn-primary">Create Project</button>
                <a href="{{ url_for('projects.project_show_user') }}"><buttontype="button" class="btn btn-success">Back to your Projects</button></a>
            </form>
        </div>
    </div>
    {% else %}
    <div class="card text-center text-dark bg-warning mb-3">
        <div class="card-body">
            <h5 class="card-title">Please sign in to create a Project</h5>
            <a href="{{ url_for('auth.login') }}"><buttontype="button" class="btn btn-success">Log In</button></a>
            <a href="{{ url_for('auth.signup') }}"><buttontype="button" class="btn btn-success">Sign Up</button></a>
            <a href="{{ url_for('projects.project_index') }}"><buttontype="button" class="btn btn-success">Back to Projects</button></a>
        </div>
    </div>
    {% endif %}
{% endblock %}

src/templates/project.html
{% extends "layout.html" %}
{% block title %}Name{% endblock %}

{% block content%}
    <div class="card text-center border-dark mb-3">
        <div class="card-header">
            By {{project.user.username}}
        </div>
        <div class="card-body">
            <h1 class="card-title">{{project.name}}</h1>
            <h3 class="card-title">Link: <a href='{{project.link}}' target='_blank'>{{project.link}}</a></h3>
            <p class="card-text">{{project.description}}</p>
            <a href="{{ url_for('feedbacks.feedback_show_project', id=project.id) }}" class="btn btn-primary">View Feedback</a>
            {% if current_user.is_authenticated and current_user.id != project.user.id %}
                <a href="{{ url_for('feedbacks.new_feedback', id=project.id) }}" class="btn btn-primary">Give Feedback</a>
            {% endif%}
            {% if current_user.is_authenticated and current_user.id == project.user.id %}
                <a href="{{ url_for('projects.revise_project', id=project.id) }}" class="btn btn-primary">Update Project</a>
                <a href="{{ url_for('projects.project_delete', id=project.id) }}" class="btn btn-primary">Delete Project</a>
                <a href="{{ url_for('projects.project_show_user') }}" class="btn btn-primary">Back to my Projects</a>
            {% endif%}
            <a href="{{ url_for('projects.project_index') }}" class="btn btn-primary">Back to all Projects</a>
        </div>
        <div class="card-footer text-muted">
            Last Updated: {{project.last_updated.strftime('%Y-%m-%d %H:%M')}}
        </div>
    </div>
{% endblock %}

src/templates/projects_index.html
{% extends "layout.html" %}

{% block content %}
    <div class="card text-center text-dark bg-light mb-3 border-dark mb-3">
        <div class="card-body">
            <h1 class="card-title">Projects</h1>
        </div>
    </div>          
    {% for project in projects %}
    <div class="card text-center border-dark mb-3">
        <div class="card-header">
            By {{project.user.username}}
        </div>
        <div class="card-body">
            <h5 class="card-title">{{project.name}}</h5>
            <p class="card-text">{{project.description}}</p>
            <a href="{{ url_for('projects.project_show', id=project.id) }}" class="btn btn-primary">See this Project</a>
        </div>
        <div class="card-footer text-muted">
            Last Updated: {{project.last_updated.strftime('%Y-%m-%d %H:%M')}}
        </div>
    </div>
    {% endfor %}

{% endblock %}

src/templates/projects_user.html
{% extends "layout.html" %}
{% block title %}Your Projects{% endblock %}

{% block content %}
    <div class="card text-center text-dark bg-light mb-3 border-dark mb-3">
        <div class="card-body">
            <h1 class="card-title">Your Projects</h1>
        </div>
    </div>          
    {% for project in projects %}
    <div class="card text-center border-dark mb-3">
        <div class="card-header">
            By {{project.user.username}}
        </div>
        <div class="card-body">
            <h5 class="card-title">{{project.name}}</h5>
            <p class="card-text">{{project.description}}</p>
            <a href="{{ url_for('projects.project_show', id=project.id) }}" class="btn btn-primary">See this Project</a>
        </div>
        <div class="card-footer text-muted">
            Last Updated: {{project.last_updated.strftime('%Y-%m-%d %H:%M')}}
        </div>
    </div>
    {% endfor %}
    <a href="{{ url_for('projects.new_project') }}" class="btn btn-primary">Create a new Project</a>
{% endblock %}

src/templates/revise_feedback.html
{% extends 'layout.html' %}

{% block content %}
    <div class="card text-center text-dark bg-light mb-3 border-dark mb-3">
        <div class="card-body">
            <h1 class="card-title">Update Feedback</h1>
        </div>
    </div>
    {% if current_user.is_authenticated %}
    <div>
        <div>
            <form action="{{ url_for('feedbacks.feedback_update', id=feedback.id) }}" method='POST'>
                <div class="mb-3">
                    <label for="text" class="form-label">Feedback:</label>
                    <textarea class="form-control" name='text' id='text' rows='12'>{{feedback.text}}</textarea>
                </div>
                <button type="submit" class="btn btn-primary">Update Feedback</button>
                <a href="{{ url_for('feedbacks.feedback_show_project', id=feedback.project_id) }}"><buttontype="button" class="btn btn-success">Back to Feedback</button></a>
            </form>
        </div>
    </div>
    {% else %}
    <div class="card text-center text-dark bg-warning mb-3">
        <div class="card-body">
            <h5 class="card-title">Please sign in to update Feedback</h5>
            <a href="{{ url_for('auth.login') }}"><buttontype="button" class="btn btn-success">Log In</button></a>
            <a href="{{ url_for('auth.signup') }}"><buttontype="button" class="btn btn-success">Sign Up</button></a>
            <a href="{{ url_for('feedbacks.feedback_show_project', id=feedback.project_id) }}"><buttontype="button" class="btn btn-success">Back to Feedback</button></a>
        </div>
    </div>
    {% endif %}
{% endblock %}

src/templates/revise_project.html
{% extends 'layout.html' %}

{% block content %}
    <div class="card text-center text-dark bg-light mb-3 border-dark mb-3">
        <div class="card-body">
            <h1 class="card-title">Update Project</h1>
        </div>
    </div>
    {% if current_user.is_authenticated %}
    <div>
        <div>
            <form action="{{ url_for('projects.project_update', id=project.id) }}" method='POST'>
                <div class="mb-3">
                    <label for="name" class="form-label">Project Name: </label>
                    <input type='text' class="form-control" name='name' id='name' value='{{project.name}}'>
                </div>
                <div class="mb-3">
                    <label for="link" class="form-label">Link: </label>
                    <input type='url' class="form-control" name='link' id='link' value='{{project.link}}'>
                </div>
                <div class="mb-3">
                    <label for="description" class="form-label">Description: </label>
                    <textarea class="form-control" name='description' id='description' rows='10'>{{project.description}}</textarea>
                </div>
                <button type="submit" class="btn btn-primary">Update Project</button>
                <a href="{{ url_for('projects.project_show_user') }}"><buttontype="button" class="btn btn-success">Back to your Projects</button></a>
            </form>
        </div>
    </div>
    {% else %}
    <div class="card text-center text-dark bg-warning mb-3">
        <div class="card-body">
            <h5 class="card-title">Please sign in to update Projects</h5>
            <a href="{{ url_for('auth.login') }}"><buttontype="button" class="btn btn-success">Log In</button></a>
            <a href="{{ url_for('auth.signup') }}"><buttontype="button" class="btn btn-success">Sign Up</button></a>
            <a href="{{ url_for('projects.project_index') }}"><buttontype="button" class="btn btn-success">Back to Projects</button></a>
        </div>
    </div>
    {% endif %}
{% endblock %}

src/templates/signup.html
{% extends 'layout.html' %}

{% block content %}
    <div class="card text-center text-dark bg-light mb-3 border-dark mb-3">
        <div class="card-body">
            <h1 class="card-title">Sign Up</h1>
        </div>
    </div>
    <div>
        <div>
            <form action="{{ url_for('auth.auth_register') }}" method='POST'>
                <div class="mb-3">
                    <label for="username" class="form-label">Username</label>
                    <input type='text' class="form-control" name='username' id='username' placeholder='Username' autofocus=''>
                </div>
                <div class="mb-3">
                    <label for="email" class="form-label">Email Address</label>
                    <input type='email' class="form-control" name='email' id='email' placeholder='name@domain.com'>
                </div>
                <div class="mb-3">
                    <label for="password" class="form-label">Password</label>
                    <input type="password" class="form-control" name='password' id="password">
                </div>
                <button type="submit" class="btn btn-primary">Sign up</button>
                <a href="{{ url_for('auth.main_page') }}"><buttontype="button" class="btn btn-success">Go Back</button></a>
            </form>
        </div>
    </div>
{% endblock %}